semantic error: Call to set.remove must have exactly one argument
 --> tests/errors/test_set2.py:6:5
  |
6 |     a.remove('error', 'error2')
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
